name: Gitflow Branch Naming

on:
    pull_request:
        types: [opened, edited, reopened]

jobs:
    check-branch-name:
        runs-on: ubuntu-latest
        steps:
            - name: Check branch name
              uses: deepakputhraya/action-branch-name@master
              with:
                  regex: '^(feature|bugfix|hotfix|release|support)\/.+'
                  allowed_prefixes: "feature,bugfix,hotfix,release,support"
                  ignore: master,develop
                  min_length: 5
                  max_length: 50
