name: Gitflow Automerge

on:
    push:
        branches:
            - master

jobs:
    merge-master-to-develop:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Merge master into develop
              uses: tukasz/direct-merge-action@master
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  source-branch: master
                  target-branch: develop
